# Generated by Django 5.0.3 on 2024-07-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0010_alter_consejodirectivo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deportes',
            new_name='Disciplinas',
        ),
        migrations.RenameModel(
            old_name='Disciplina',
            new_name='Subdisciplinas',
        ),
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='subdisciplinas',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Subdisciplinas'},
        ),
        migrations.RenameField(
            model_name='eventodeportivo',
            old_name='disciplina',
            new_name='subdisciplina',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='deporte',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='tabladeposiciones',
            old_name='disciplina',
            new_name='subdisciplina',
        ),
    ]
