# Generated by Django 5.0.3 on 2024-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0011_rename_deportes_disciplinas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
