# Generated by Django 5.0.3 on 2024-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0012_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
