# Generated by Django 5.0.3 on 2024-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0013_alter_categoria_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='logo',
            field=models.ImageField(default='logos/descarga_1.png', upload_to='logos/'),
        ),
    ]
