# Generated by Django 5.0.3 on 2024-07-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0015_subdisciplinas_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdisciplinas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='subdisciplinas',
            name='puntos',
        ),
    ]
