# Generated by Django 5.0.3 on 2024-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0016_remove_subdisciplinas_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventodeportivo',
            options={'verbose_name': 'Evento deportivo', 'verbose_name_plural': 'Eventos deportivos'},
        ),
        migrations.AddField(
            model_name='eventodeportivo',
            name='estado',
            field=models.CharField(choices=[('EN_JUEGO', 'En Juego'), ('FINALIZADO', 'Finalizado'), ('ACABADO', 'Acabado')], default='EN_JUEGO', max_length=10),
        ),
        migrations.AddField(
            model_name='eventodeportivo',
            name='nombre_evento',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
