# Generated by Django 5.0.3 on 2024-08-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0017_alter_eventodeportivo_options_eventodeportivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.eventodeportivo'),
        ),
        migrations.RemoveField(
            model_name='subdisciplinas',
            name='disciplina',
        ),
        migrations.AlterField(
            model_name='tabladeposiciones',
            name='subdisciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdisciplinas', to='deportes.promocion'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='subdisciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='deportes.promocion'),
        ),
        migrations.AlterModelOptions(
            name='excadete',
            options={'verbose_name': 'Ex cadete', 'verbose_name_plural': 'Ex cadetes'},
        ),
        migrations.AlterModelOptions(
            name='participacion',
            options={'verbose_name': 'Participación', 'verbose_name_plural': 'Participaciones'},
        ),
        migrations.AlterModelOptions(
            name='tabladeposiciones',
            options={'verbose_name': 'Tabla de posiciones', 'verbose_name_plural': 'Tablas de posiciones'},
        ),
        migrations.RemoveField(
            model_name='eventodeportivo',
            name='resultados',
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='nombre_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Disciplinas',
        ),
        migrations.DeleteModel(
            name='Subdisciplinas',
        ),
    ]
