# Generated by Django 5.0.3 on 2024-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0018_alter_resultado_disciplina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajedrez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='ajedrez/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Atletismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='atletismo/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Baloncesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='baloncesto/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Billas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='billas/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='CrossCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='cross_country/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Cubilete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='cubilete/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Fulbito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='fulbito/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='InauguracionDesfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='inauguracion_desfile/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Natacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='natacion/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='Pena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='pena/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='TenisDeMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='tenis_de_mesa/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
        migrations.CreateModel(
            name='TiroAlSapo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='tiro_al_sapo/')),
            ],
            options={
                'verbose_name': 'Subdisciplina',
                'verbose_name_plural': 'Subdisciplina',
            },
        ),
    ]
