# Generated by Django 5.0.3 on 2024-08-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0019_ajedrez_atletismo_baloncesto_billas_crosscountry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baloncesto',
            options={'verbose_name': 'Subdisciplinaaaaaa', 'verbose_name_plural': 'Subdisciplina'},
        ),
    ]
