# Generated by Django 5.0.3 on 2024-08-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0020_alter_baloncesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baloncesto',
            options={'verbose_name': 'Baloncesto', 'verbose_name_plural': 'Subdisciplina'},
        ),
    ]
