# Generated by Django 5.0.3 on 2024-08-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0021_alter_baloncesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baloncesto',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Baloncesto'},
        ),
    ]
