# Generated by Django 5.0.3 on 2024-08-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0022_alter_baloncesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajedrez',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Ajedrez'},
        ),
        migrations.AlterModelOptions(
            name='atletismo',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Atletismo'},
        ),
        migrations.AlterModelOptions(
            name='billas',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Billas'},
        ),
        migrations.AlterModelOptions(
            name='crosscountry',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'CrossCountry'},
        ),
        migrations.AlterModelOptions(
            name='cubilete',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Cubilete'},
        ),
        migrations.AlterModelOptions(
            name='fulbito',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Fulbito'},
        ),
        migrations.AlterModelOptions(
            name='inauguraciondesfile',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'InauguracionDesfile'},
        ),
        migrations.AlterModelOptions(
            name='natacion',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Natacion'},
        ),
        migrations.AlterModelOptions(
            name='pena',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'Pena'},
        ),
        migrations.AlterModelOptions(
            name='tenisdemesa',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'TenisDeMesa'},
        ),
        migrations.AlterModelOptions(
            name='tiroalsapo',
            options={'verbose_name': 'Subdisciplina', 'verbose_name_plural': 'TiroAlSapo'},
        ),
    ]
