# Generated by Django 5.0.3 on 2024-08-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0023_alter_ajedrez_options_alter_atletismo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='promocion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion1', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion10', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion11', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion12', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion13', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion14', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion15', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion16', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion17', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion18', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion19', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion2', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion20', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion3', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion4', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion5', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion6', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion7', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion8', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='promocion9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_promocion9', to='deportes.promocion'),
        ),
    ]
