# Generated by Django 5.0.3 on 2024-08-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0024_categoria_promocion1_categoria_promocion10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baloncesto',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
    ]
