# Generated by Django 5.0.3 on 2024-08-01 22:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0025_alter_baloncesto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajedrez',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='billas',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='crosscountry',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='cubilete',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='fulbito',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='inauguraciondesfile',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='pena',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='tenisdemesa',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='tiroalsapo',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.RenameField(
            model_name='crosscountry',
            old_name='nombre',
            new_name='lugar',
        ),
        migrations.RemoveField(
            model_name='crosscountry',
            name='imagen',
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='estado',
            field=models.CharField(choices=[('EN_JUEGO', 'En Juego'), ('FINALIZADO', 'Finalizado'), ('ACABADO', 'Acabado')], default='EN_JUEGO', max_length=10),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='nombre_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
