# Generated by Django 5.0.3 on 2024-08-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0026_alter_ajedrez_options_alter_billas_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajedrez',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Ajedrez'},
        ),
        migrations.AlterModelOptions(
            name='baloncesto',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Baloncesto'},
        ),
        migrations.AlterModelOptions(
            name='billas',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Billas'},
        ),
        migrations.AlterModelOptions(
            name='crosscountry',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'CrossCountry'},
        ),
        migrations.AlterModelOptions(
            name='cubilete',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Cubilete'},
        ),
        migrations.AlterModelOptions(
            name='fulbito',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Fulbito'},
        ),
        migrations.AlterModelOptions(
            name='inauguraciondesfile',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Inauguraciones'},
        ),
        migrations.AlterModelOptions(
            name='pena',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'Peña'},
        ),
        migrations.AlterModelOptions(
            name='tenisdemesa',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'TenisDeMesa'},
        ),
        migrations.AlterModelOptions(
            name='tiroalsapo',
            options={'verbose_name': 'EVENTO', 'verbose_name_plural': 'TiroAlSapo'},
        ),
    ]
