# Generated by Django 5.0.3 on 2024-08-01 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0027_alter_ajedrez_options_alter_baloncesto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosscountry',
            name='duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='jugadores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='promocion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosscountry_promocion1', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='promocion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosscountry_promocion2', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='promocion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosscountry_promocion3', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='promocion4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosscountry_promocion4', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='promocion5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosscountry_promocion5', to='deportes.promocion'),
        ),
    ]
