# Generated by Django 5.0.3 on 2024-08-01 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0028_crosscountry_duracion_crosscountry_jugadores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosCross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_lugar_nombre', models.CharField(max_length=255)),
                ('segundo_lugar_nombre', models.CharField(max_length=255)),
                ('tercer_lugar_nombre', models.CharField(max_length=255)),
                ('otros_puestos_nombre', models.TextField()),
                ('primer_lugar_puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('segundo_lugar_puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tercer_lugar_puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otros_puestos_puntaje', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.crosscountry')),
            ],
            options={
                'verbose_name': 'Resultados Cross Country',
                'verbose_name_plural': 'Resultados Cross Country',
            },
        ),
    ]
