# Generated by Django 5.0.3 on 2024-08-01 23:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0029_resultadoscross'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosAtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('duracion', models.DurationField()),
                ('promociones', models.ManyToManyField(related_name='eventos_atl', to='deportes.promocion')),
                ('subdisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.atletismo')),
            ],
            options={
                'verbose_name': 'Evento de Atletismo',
                'verbose_name_plural': 'Eventos de Atletismo',
            },
        ),
    ]
