# Generated by Django 5.0.3 on 2024-08-01 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0030_eventosatl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventosatl',
            name='promociones',
        ),
        migrations.AddField(
            model_name='eventosatl',
            name='promocion1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletismo_promocion1', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='eventosatl',
            name='promocion2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletismo_promocion2', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='eventosatl',
            name='promocion3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletismo_promocion3', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='eventosatl',
            name='promocion4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletismo_promocion4', to='deportes.promocion'),
        ),
        migrations.AddField(
            model_name='eventosatl',
            name='promocion5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletismo_promocion5', to='deportes.promocion'),
        ),
        migrations.CreateModel(
            name='ResultadosATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('primer_lugar_nombre', models.CharField(max_length=100)),
                ('primer_lugar_puntaje', models.PositiveIntegerField()),
                ('segundo_lugar_nombre', models.CharField(max_length=100)),
                ('segundo_lugar_puntaje', models.PositiveIntegerField()),
                ('tercer_lugar_nombre', models.CharField(max_length=100)),
                ('tercer_lugar_puntaje', models.PositiveIntegerField()),
                ('otros_puestos', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.eventosatl')),
            ],
            options={
                'verbose_name': 'Resultado de Atletismo',
                'verbose_name_plural': 'Resultados de Atletismo',
            },
        ),
    ]
